# Generated by Django 5.1.5 on 2025-02-03 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='名無しさん', max_length=15, validators=[django.core.validators.RegexValidator(message='使用できるのは英数字、ひらがな、カタカナ、漢字のみです。', regex='^[a-zA-Z0-9ぁ-んァ-ン一-龥]+$')]),
        ),
    ]
