# Generated by Django 5.1.5 on 2025-02-03 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='名無しさん', max_length=15, validators=[django.core.validators.RegexValidator(message='記号は使用できません。', regex='^[a-zA-Z0-9ぁ-んァ-ン一-龥ー]+$')]),
        ),
    ]
